# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document', models.FileField(upload_to='pdfs/', verbose_name='Document PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
            },
        ),
    ]
